#!/bin/bash

set -x

if [ $EUID -ne 0 ]; then
        exec sudo bash $0
fi

rfkill unblock bluetooth

systemctl restart bluetooth

sleep 3

bluetoothctl --timeout 3 <<EOF
power on
agent on
scan on
EOF
