#!/bin/bash

set -e

if [ $EUID -ne 0 ]; then
        exec sudo bash $0
fi

NO_TURBO=/sys/devices/system/cpu/intel_pstate/no_turbo

V=$(cat $NO_TURBO)
INV=$((1-V))
echo -n $INV  > $NO_TURBO

if [ $INV -eq 0 ]; then
        echo "TURBO ON"
else
        echo "TURBO OFF"
fi
